// DISCLAIMER: this test file was generated by Deepseek R1
package merkletree

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProof(t *testing.T) {
	t.Parallel()

	t.Run("rejects unknown leaf", func(t *testing.T) {
		input := generateRandomInputs(t, 4)
		tree, err := New(nil, input)
		require.NoError(t, err)

		unknown := []byte("not-in-tree")
		proof, err := tree.ProofFromInput(unknown)
		assert.ErrorIs(t, err, ErrProofInvalidLeaf)
		assert.Nil(t, proof)
	})

	t.Run("generates valid proof for each leaf (even count, no domain sep)", func(t *testing.T) {
		input := generateRandomInputs(t, 4)
		tree, err := New(&Config{DomainSeperation: false}, input)
		require.NoError(t, err)

		for i, data := range input {
			proof, err := tree.ProofFromInput(data)
			require.NoError(t, err, "proof for leaf %d", i)
			require.NotNil(t, proof)

			// With carry-up, proof length varies but should be > 0 for even counts > 1
			assert.Greater(t, len(proof.Siblings), 0)
			// Maximum possible siblings is tree.Depth-1 (or tree.Depth if top level has 2 nodes)
			assert.LessOrEqual(t, len(proof.Siblings), tree.Depth)

			// Verify using your Verify func
			ok, err := Verify(data, tree.Root, proof, &Config{DomainSeperation: false})
			require.NoError(t, err)
			assert.True(t, ok, "verification failed for leaf %d", i)
		}
	})

	t.Run("proof verification succeeds with domain separation enabled", func(t *testing.T) {
		input := generateRandomInputs(t, 5) // odd count to test carry-up
		tree, err := New(&Config{DomainSeperation: true}, input)
		require.NoError(t, err)

		for i, data := range input {
			proof, err := tree.ProofFromInput(data)
			require.NoError(t, err)

			ok, err := Verify(data, tree.Root, proof, &Config{DomainSeperation: true})
			require.NoError(t, err)
			assert.True(t, ok, "domain sep: verification failed for leaf %d", i)
		}
	})

	t.Run("proof fails verification when leaf is wrong", func(t *testing.T) {
		input := generateRandomInputs(t, 4)
		tree, err := New(nil, input)
		require.NoError(t, err)

		proof, err := tree.ProofFromInput(input[0])
		require.NoError(t, err)

		// Wrong data
		wrongData := generateRandomInputs(t, 1)[0]
		ok, err := Verify(wrongData, tree.Root, proof, nil)
		require.NoError(t, err)
		assert.False(t, ok, "should fail for wrong leaf data")
	})

	t.Run("proof fails when sibling tampered", func(t *testing.T) {
		input := generateRandomInputs(t, 4)
		tree, err := New(nil, input)
		require.NoError(t, err)

		proof, err := tree.ProofFromInput(input[0])
		require.NoError(t, err)
		require.NotEmpty(t, proof.Siblings, "test requires at least one sibling")

		// Tamper with first sibling
		tamperedProof := &Proof{
			PathBits: proof.PathBits,
			Siblings: make([][]byte, len(proof.Siblings)),
		}
		copy(tamperedProof.Siblings, proof.Siblings)
		tamperedProof.Siblings[0] = bytes.Repeat([]byte{0xAA}, 32) // arbitrary tamper

		ok, err := Verify(input[0], tree.Root, tamperedProof, nil)
		require.NoError(t, err)
		assert.False(t, ok, "should fail with tampered sibling")
	})

	t.Run("proof fails with wrong root", func(t *testing.T) {
		input := generateRandomInputs(t, 4)
		tree, err := New(nil, input)
		require.NoError(t, err)

		proof, err := tree.ProofFromInput(input[0])
		require.NoError(t, err)

		wrongRoot := bytes.Repeat([]byte{0xFF}, len(tree.Root))
		ok, err := Verify(input[0], wrongRoot, proof, nil)
		require.NoError(t, err)
		assert.False(t, ok, "should fail with incorrect root")
	})

	t.Run("proof path and siblings correct length", func(t *testing.T) {
		tests := []struct {
			leafCount   int
			maxSiblings int
		}{
			{2, 1}, // 2 leaves -> depth 2, max 1 sibling
			{3, 2}, // 3 leaves -> depth 3, leaf 0 has 2 siblings, leaf 2 has 1
			{4, 2}, // 4 leaves -> depth 3, all leaves have 2 siblings
			{8, 3}, // 8 leaves -> depth 4, all leaves have 3 siblings
			{9, 4}, // 9 leaves -> depth 5, varies
		}

		for _, tt := range tests {
			input := generateRandomInputs(t, tt.leafCount)
			tree, err := New(nil, input)
			require.NoError(t, err)

			// Test first leaf
			proof, err := tree.ProofFromInput(input[0])
			require.NoError(t, err)

			// Proof length should be reasonable
			assert.GreaterOrEqual(t, len(proof.Siblings), 1, "should have at least one sibling for %d leaves", tt.leafCount)
			assert.LessOrEqual(t, len(proof.Siblings), tt.maxSiblings, "too many siblings for %d leaves", tt.leafCount)

			// Index should be within valid range
			assert.True(t, proof.PathBits < (1<<tree.Depth), "path too large")

			// Verify the proof works
			ok, err := Verify(input[0], tree.Root, proof, nil)
			require.NoError(t, err)
			assert.True(t, ok)
		}
	})

	t.Run("single leaf tree", func(t *testing.T) {
		input := generateRandomInputs(t, 1)
		tree, err := New(nil, input)
		require.NoError(t, err)

		proof, err := tree.ProofFromInput(input[0])
		require.NoError(t, err)

		// Single leaf should have empty siblings
		assert.Empty(t, proof.Siblings, "single leaf should have no siblings")
		assert.Equal(t, uint64(0), proof.PathBits)

		// Verification should work
		ok, err := Verify(input[0], tree.Root, proof, nil)
		require.NoError(t, err)
		assert.True(t, ok)

		// Root should equal leaf hash
		leaf, err := sproutLeaf(input[0], tree.hashFunc, tree.DomainSeperation)
		require.NoError(t, err)
		assert.True(t, bytes.Equal(tree.Root, leaf))
	})

	t.Run("odd leaf has shorter proof", func(t *testing.T) {
		input := generateRandomInputs(t, 3) // odd number
		tree, err := New(nil, input)
		require.NoError(t, err)

		// Proof for first leaf (paired)
		proof0, err := tree.ProofFromInput(input[0])
		require.NoError(t, err)

		// Proof for last leaf (odd one out)
		proof2, err := tree.ProofFromInput(input[2])
		require.NoError(t, err)

		// The odd leaf should have a shorter proof (carried up)
		assert.Less(t, len(proof2.Siblings), len(proof0.Siblings),
			"odd leaf should have shorter proof (carried up without sibling at some level)")

		// Both should verify correctly
		ok0, err := Verify(input[0], tree.Root, proof0, nil)
		require.NoError(t, err)
		assert.True(t, ok0)

		ok2, err := Verify(input[2], tree.Root, proof2, nil)
		require.NoError(t, err)
		assert.True(t, ok2)
	})
}

func TestProof_6Leaves_4thChunk(t *testing.T) {
	// Simulate a 5,506 byte file = 6 chunks (5 full + 1 partial)
	chunks := [][]byte{
		bytes.Repeat([]byte{0x00}, 1024), // Chunk 0
		bytes.Repeat([]byte{0x01}, 1024), // Chunk 1
		bytes.Repeat([]byte{0x02}, 1024), // Chunk 2
		bytes.Repeat([]byte{0x03}, 1024), // Chunk 3
		bytes.Repeat([]byte{0x04}, 1024), // Chunk 4 (the one we're testing)
		bytes.Repeat([]byte{0x05}, 386),  // Chunk 5 (partial)
	}

	config := &Config{
		DomainSeperation: true,
		XXH128:           true,
	}

	// Build the tree
	tree, err := New(config, chunks)
	require.NoError(t, err)
	require.NotNil(t, tree)

	t.Logf("Tree depth: %d", tree.Depth)
	t.Logf("Leaf count: %d", tree.LeafCount)
	for i, level := range tree.nodes {
		t.Logf("Level %d: %d nodes", i, len(level))
	}

	// Expected structure for 6 leaves:
	// Level 0: 6 nodes
	// Level 1: 3 nodes
	// Level 2: 2 nodes
	// Level 3: 1 node (root)
	assert.Equal(t, 4, tree.Depth)
	assert.Len(t, tree.nodes[0], 6)
	assert.Len(t, tree.nodes[1], 3)
	assert.Len(t, tree.nodes[2], 2)
	assert.Len(t, tree.nodes[3], 1)

	// Generate proof for the 4th chunk (index 4)
	proof, err := tree.Proof(4)
	require.NoError(t, err)
	require.NotNil(t, proof)

	t.Logf("Proof for chunk 4: Index=%d (0b%b), Siblings=%d", proof.PathBits, proof.PathBits, len(proof.Siblings))

	// Expected proof for leaf 4:
	// - Level 0: sibling is leaf 5
	// - Level 1: no sibling (H45 carried up)
	// - Level 2: sibling is H0123 (hash of left subtree)
	// Total siblings: 2
	assert.Len(t, proof.Siblings, 2, "Expected 2 siblings for leaf 4")

	// Verify the proof
	valid, err := Verify(chunks[4], tree.Root, proof, config)
	require.NoError(t, err)
	assert.True(t, valid, "Proof verification failed for chunk 4")

	// Also verify all other chunks to ensure overall correctness
	for i, chunk := range chunks {
		proof, err := tree.ProofFromInput(chunk)
		require.NoError(t, err, "Failed to generate proof for chunk %d", i)

		valid, err := Verify(chunk, tree.Root, proof, config)
		require.NoError(t, err, "Verification error for chunk %d", i)
		assert.True(t, valid, "Proof verification failed for chunk %d", i)

		t.Logf("Chunk %d verified successfully with %d siblings", i, len(proof.Siblings))
	}

	// Detailed verification of proof structure
	t.Run("ProofStructure", func(t *testing.T) {
		// Leaf 0 (first): should have siblings at level 0 (leaf 1), level 1 (H23), level 2 (H45)
		proof0, _ := tree.Proof(0)
		assert.Len(t, proof0.Siblings, 3, "Leaf 0 should have 3 siblings")

		// Leaf 4 (our test case): should have siblings at level 0 (leaf 5) and level 2 (H0123)
		proof4, _ := tree.Proof(4)
		assert.Len(t, proof4.Siblings, 2, "Leaf 4 should have 2 siblings")

		// Leaf 5 (last): should have sibling at level 0 (leaf 4) and level 2 (H0123)
		proof5, _ := tree.Proof(5)
		assert.Len(t, proof5.Siblings, 2, "Leaf 5 should have 2 siblings")
	})
}
